name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Ruff-and-Gunicorn-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Install all dependencies
        run: |
          uv sync --dev --frozen
          
      - name: Run ruff linter
        run: |
          uv run ruff check .

      - name: Run ruff formatter
        run: |
          uv run ruff format --check .
          
      - name: Test gunicorn server
        run: |
          uv run gunicorn api:app --bind 127.0.0.1:8000 --workers 2 --timeout 5 --log-level debug --check